<?php
// Start with output buffering to catch any stray output
ob_start();

session_start();
date_default_timezone_set('Asia/Kolkata');
// Check authentication first
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

require_once 'config.php';
require_once 'db_connection.php';

$user_id = $_SESSION['user_id'];

// Fetch user and business details
$user_sql = "SELECT u.name, u.email, u.phone, u.address, 
                    b.business_name, b.business_address, b.designation
             FROM users u 
             LEFT JOIN business_info b ON u.id = b.user_id 
             WHERE u.id = ?";
$stmt = $conn->prepare($user_sql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$user_data = $result->fetch_assoc();
$stmt->close();

// Fetch current subscription with package price
$subscription_sql = "SELECT p.name as package_name, s.start_date, p.price as package_price
                     FROM subscriptions s 
                     JOIN packages p ON s.package_id = p.id 
                     WHERE s.user_id = ? AND s.status = 'active' 
                     ORDER BY s.start_date DESC LIMIT 1";
$stmt_sub = $conn->prepare($subscription_sql);
$stmt_sub->bind_param("i", $user_id);
$stmt_sub->execute();
$subscription_result = $stmt_sub->get_result();
$subscription_data = $subscription_result->fetch_assoc();
$stmt_sub->close();

$conn->close();

// Clear any output that might have been generated
ob_clean();

// Check if TCPDF exists, if not use a simple approach
if (file_exists('tcpdf/tcpdf.php')) {
    generateWithTCPDF($user_data, $subscription_data);
} else {
    generateSimplePDF($user_data, $subscription_data);
}

function generateWithTCPDF($user_data, $subscription_data) {
    require_once('tcpdf/tcpdf.php');

    // Create custom TCPDF class to handle background on all pages
    class CustomTCPDF extends TCPDF {
        // Page header
        public function Header() {
            // Set background color for all pages
            $this->SetFillColor(255, 233, 220);
            $this->Rect(0, 0, $this->getPageWidth(), $this->getPageHeight(), 'F');
            
            // Add logo on ALL pages
            $logo_path = 'images/deegeecard_logo.png';
            if (file_exists($logo_path)) {
                // Bigger logo - 3x size (90 width instead of 30)
                // Calculate center position: (page width - logo width) / 2
                $page_width = $this->getPageWidth();
                $logo_width = 90;
                $x_position = ($page_width - $logo_width) / 2;
                
                // Reduced margin bottom from logo (from 55 to 35 - 50% decrease)
                $this->Image($logo_path, $x_position, 15, 90, 0, 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
                $this->SetY(35); // Reduced from 55 to 35 (50% decrease)
            } else {
                $this->SetY(25);
            }
            
            // Title on first page only
            if ($this->page == 1) {
                $this->SetFont('helvetica', 'B', 20);
                $this->SetTextColor(51, 51, 51);
                $this->Cell(0, 10, 'DeeGeeCard – Service Agreement', 0, 1, 'C');
                $this->Ln(5);
            }
        }
        
        // Page footer
        public function Footer() {
            // Position closer to bottom (reduced from -25 to -20)
            $this->SetY(-35);
            $this->SetFont('helvetica', 'I', 8);
            $this->SetTextColor(128, 128, 128);
            
            // Add the new agreement text
            $this->Cell(0, 6, 'This is a system-generated agreement and shall be considered valid without a physical signature, unless expressly requested by either party.', 0, 1, 'C');
            
            // Page info with reduced margin (moved up closer to the agreement text)
            $this->Cell(0, 6, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages() . ' - Generated by DeeGeeCard System on ' . date('d/m/Y H:i:s'), 0, 0, 'C');
            
            // Add small logo in footer on all pages
            if (file_exists('images/deegeecard_logo.png')) {
                $this->Image('images/deegeecard_logo.png', 85, $this->GetY() + 8, 30, 0, 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
            }
        }
    }

    // Create new PDF document with custom class
    $pdf = new CustomTCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    // Set document information
    $pdf->SetCreator('DeeGeeCard');
    $pdf->SetAuthor('DeeGeeCard');
    $pdf->SetTitle('Service Agreement');

    // Remove default header/footer (we're using custom ones)
    $pdf->setPrintHeader(true);
    $pdf->setPrintFooter(true);

    // Set margins - reduced top margin due to decreased logo margin
    $pdf->SetMargins(15, 50, 15); // Reduced from 70 to 50 (accommodates reduced logo margin)
    $pdf->SetAutoPageBreak(true, 30);

    // Add first page
    $pdf->AddPage();

    // Agreement content
    generateAgreementContent($pdf, $user_data, $subscription_data);

    // Output PDF
    $client_name = $user_data['business_name'] ?: $user_data['name'];
    $filename = 'DeeGeeCard_Service_Agreement_' . preg_replace('/[^a-zA-Z0-9]/', '_', $client_name) . '_' . date('Y-m-d') . '.pdf';
    
    $pdf->Output($filename, 'D');
    exit;
}

function generateSimplePDF($user_data, $subscription_data) {
    // Fallback: Create a simple text agreement if TCPDF is not available
    $client_name = $user_data['business_name'] ?: $user_data['name'];
    $filename = 'DeeGeeCard_Service_Agreement_' . preg_replace('/[^a-zA-Z0-9]/', '_', $client_name) . '_' . date('Y-m-d') . '.txt';
    
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    
    echo "DeeGeeCard – Service Agreement\n";
    echo "================================\n\n";
    echo "This Service Agreement is entered into on " . date('jS \d\a\y \o\f F, Y') . "\n\n";
    
    echo "Service Provider:\n";
    echo "DeeGeeCard\n";
    echo "A product of Digital Growth Solutions\n";
    echo "Registered Address: Mira Road, Thane, Maharashtra\n";
    echo "Contact | support@deegeecard.com\n\n";
    
    echo "Client/Restaurant Name: " . ($user_data['business_name'] ?: $user_data['name']) . "\n";
    echo "Address: " . ($user_data['business_address'] ?: $user_data['address']) . "\n";
    echo "Owner/Manager Name: " . $user_data['name'] . "\n";
    echo "Phone: " . $user_data['phone'] . " | Email: " . $user_data['email'] . "\n\n";
    
    echo "Please install TCPDF library for proper PDF generation.\n";
    echo "Download from: https://github.com/tecnickcom/tcpdf\n";
    exit;
}

function generateAgreementContent($pdf, $user_data, $subscription_data) {
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(51, 51, 51);

    // Use start_date from subscriptions table for effective date
    $effective_date = 'N/A';
    if (!empty($subscription_data['start_date'])) {
        $effective_date = date('jS \d\a\y \o\f F, Y', strtotime($subscription_data['start_date']));
    } else {
        $effective_date = date('jS \d\a\y \o\f F, Y');
    }

    // Get package price from packages table
    $package_price = 'Rs.9,999';
    if (!empty($subscription_data['package_price'])) {
        $package_price = 'Rs.' . number_format($subscription_data['package_price']);
    }

    // Effective Date
    $pdf->MultiCell(0, 10, "This Service Agreement (\"Agreement\") is entered into on this {$effective_date} (\"Effective Date\"), by and between:", 0, 'L');
    $pdf->Ln(2);

    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->MultiCell(0, 10, "DeeGeeCard\nA product of Digital Growth Solutions\nRegistered Address: Mira Road, Thane, Maharashtra\nContact | support@deegeecard.com\n(Hereinafter referred to as the \"Service Provider\")", 0, 'L');
    $pdf->Ln(2);

    $pdf->SetFont('helvetica', '', 10);
    $pdf->MultiCell(0, 10, "AND", 0, 'C');
    $pdf->Ln(2);

    // Client Information
    $client_name = $user_data['business_name'] ?: $user_data['name'];
    $client_address = $user_data['business_address'] ?: $user_data['address'];
    $owner_name = $user_data['name'];
    $phone = $user_data['phone'];
    $email = $user_data['email'];
    $designation = $user_data['designation'] ?: 'Owner/Manager';

    $pdf->SetFont('helvetica', 'B', 10);
    $pdf->MultiCell(0, 10, "Client/Restaurant Name: {$client_name}\nAddress: {$client_address}\n{$designation} Name: {$owner_name}\nPhone: {$phone}   |   Email: {$email}\n(Hereinafter referred to as the \"Client\")", 0, 'L');

    $pdf->Ln(6);

    // Agreement Sections - Compact version to fit in 2 pages
    $sections = [
        '1. Purpose' => "The purpose of this Agreement is to define the terms under which the Service Provider will offer the DeeGeeCard restaurant digital platform and related services to the Client.",
        
        '2. Services Provided' => "The Service Provider agrees to provide:\n• Restaurant Ordering Website fully branded\n• Android Mobile Application\n• Admin Management Application\n• 1000 QR Code Visiting Cards\n• Bulk WhatsApp Marketing Panel\n• Direct Payment Gateway Integration\n• Google, Instagram, Facebook, YouTube Integrations\n• Technical Setup within same day",
        
        '3. Term and Renewal' => "Valid for one year from Effective Date.\nRenewal: {$package_price}/year (subject to revision).\nNo refunds after activation.",
        
        '4. Fees and Payments' => "Client agrees to pay {$package_price}/year.\nPayment in full, in advance.\nService Provider may revise pricing upon renewal.",
        
        '5. Responsibilities of the Client' => "Client agrees to:\n• Provide accurate restaurant details\n• Ensure legal, original content\n• Manage customer orders & disputes\n• Approve artwork timely\n• Use system responsibly",
        
        '6. Ownership & Intellectual Property' => "DeeGeeCard platform rights remain with Service Provider.\nClient receives limited license during subscription.\nClient's brand assets remain Client's property.",
        
        '7. Direct Payments' => "Customer payments go directly to Client's bank account.\nService Provider not responsible for payment issues.",
        
        '8. Data & Confidentiality' => "Customer data belongs to Client.\nService Provider won't misuse or share data.",
        
        '9. Support & Maintenance' => "Technical support via WhatsApp, email, or call.\nUpdates at Service Provider's discretion.",
        
        '10. Limitations & Liability' => "Service Provider not responsible for:\n• Restaurant operations & quality\n• Customer reviews\n• Internet/API outages\nMax liability: fees paid by Client",
        
        '11. Termination' => "Service Provider may terminate if Client:\n• Engages in illegal activity\n• Misuses platform\n• Fails to comply with terms\nNo refunds upon termination.",
        
        '12. Indemnity' => "Client agrees to indemnify Service Provider from claims arising from restaurant operations or platform misuse.",
        
        '13. Governing Law' => "Governed by laws of India. Jurisdiction: Mumbai courts."
    ];

    // Add sections to PDF with compact spacing
    foreach ($sections as $title => $content) {
        // Check if we need a new page
        if ($pdf->GetY() > 240) {
            $pdf->AddPage();
        }
        
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->SetFillColor(255, 233, 220);
        $pdf->Cell(0, 8, $title, 0, 1, 'L', true);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->MultiCell(0, 6, $content, 0, 'L');
        $pdf->Ln(4);
    }
}
?>